function [opciones_entrenamiento, replayBuffer] = especificarOpcionesEntrenamiento()
    opciones_entrenamiento = trainingOptions('adam', ...
        'MiniBatchSize', 64, ...
        'MaxEpochs', 1000, ...
        'InitialLearnRate', 1e-4, ...
        'Verbose', false, ...
        'Plots', 'training-progress' );

    replayBuffer = rlReplayMemory(100000);
end